/**
 * Feature type definitions
 * Core types for feature/task management
 */

// ============================================================================
// Feature Status and Origin Types
// ============================================================================

/**
 * Feature status values
 * - failing: Not yet implemented or incomplete
 * - passing: Acceptance criteria met
 * - blocked: External dependency blocking progress
 * - needs_review: Potentially affected by recent changes
 * - failed: Implementation attempted but verification failed
 * - deprecated: No longer needed, superseded by another feature
 */
export type FeatureStatus =
  | "failing"
  | "passing"
  | "blocked"
  | "needs_review"
  | "failed"
  | "deprecated";

/**
 * TDD enforcement mode for the project
 * Controls how strictly test requirements are enforced
 *
 * - strict: Tests REQUIRED by default, check/done commands fail without tests.
 *   All features auto-migrate to testRequirements.unit.required: true.
 *   Enforces RED → GREEN → REFACTOR workflow.
 *
 * - recommended: Tests suggested but not enforced (default behavior).
 *   TDD guidance is shown but verification can proceed without tests.
 *
 * - disabled: No TDD guidance or enforcement.
 *   Verification uses AI analysis only.
 */
export type TDDMode = "strict" | "recommended" | "disabled";

/**
 * How the feature was created/discovered
 */
export type FeatureOrigin =
  | "init-auto" // Auto-generated during init
  | "init-from-routes" // Derived from route definitions
  | "init-from-tests" // Derived from test files
  | "manual" // Manually added by user
  | "replan"; // Added during replanning

/**
 * Task type classification for Universal Verification Strategy (UVS)
 * Determines which verification strategies are appropriate for a task
 *
 * - code: Software development tasks (tests, typecheck, lint, build)
 * - ops: Operations/infrastructure tasks (scripts, commands, deployments)
 * - data: Data processing tasks (pipelines, migrations, ETL)
 * - infra: Infrastructure tasks (provisioning, configuration)
 * - manual: Tasks requiring human review/approval
 */
export type TaskType = "code" | "ops" | "data" | "infra" | "manual";

// ============================================================================
// Verification Summary
// ============================================================================

/**
 * Summary of verification result to embed in Feature
 */
export interface FeatureVerificationSummary {
  /** Last verification timestamp (ISO 8601) */
  verifiedAt: string;
  /** Verification verdict */
  verdict: "pass" | "fail" | "needs_review";
  /** Agent that performed verification */
  verifiedBy: string;
  /** Git commit hash at verification time */
  commitHash?: string;
  /** Brief summary of the verification result */
  summary: string;
}

// ============================================================================
// Test Requirements
// ============================================================================

/**
 * Unit test requirements for TDD workflow
 */
export interface UnitTestRequirements {
  /** Whether unit tests are required for this feature */
  required: boolean;
  /** Glob pattern for test files */
  pattern?: string;
  /** Expected test case names derived from acceptance criteria */
  cases?: string[];
}

/**
 * E2E test requirements for TDD workflow
 */
export interface E2ETestRequirements {
  /** Whether E2E tests are required for this feature */
  required: boolean;
  /** Glob pattern for E2E test files */
  pattern?: string;
  /** Playwright tags for filtering */
  tags?: string[];
  /** Expected scenario names derived from acceptance criteria */
  scenarios?: string[];
}

/**
 * Test requirements for TDD workflow
 * When defined, verification uses test execution instead of AI analysis
 */
export interface TestRequirements {
  /** Unit test requirements */
  unit?: UnitTestRequirements;
  /** E2E test requirements */
  e2e?: E2ETestRequirements;
}

// ============================================================================
// TDD Guidance
// ============================================================================

/**
 * Cached TDD guidance generated by AI
 * Stored in feature to avoid regeneration
 */
export interface CachedTDDGuidance {
  /** Generation timestamp (ISO 8601) */
  generatedAt: string;
  /** Agent that generated this (claude/gemini/codex) */
  generatedBy: string;
  /** Feature version when generated (for invalidation) */
  forVersion: number;
  /** Suggested test file paths */
  suggestedTestFiles: {
    unit: string[];
    e2e: string[];
  };
  /** Unit test cases with assertions */
  unitTestCases: Array<{
    name: string;
    assertions: string[];
  }>;
  /** E2E scenarios (if applicable) */
  e2eScenarios: Array<{
    name: string;
    steps: string[];
  }>;
  /** Detected/suggested test framework */
  frameworkHint?: string;
}

// ============================================================================
// Feature Interface
// ============================================================================

/**
 * Single feature entry in the feature list
 */
export interface Feature {
  /** Unique identifier, e.g., "chat.message.edit" */
  id: string;
  /** Human-readable description */
  description: string;
  /** Parent module/subsystem */
  module: string;
  /** Priority (1 = highest) */
  priority: number;
  /** Current status */
  status: FeatureStatus;
  /** List of acceptance criteria */
  acceptance: string[];
  /** Task IDs this task depends on */
  dependsOn: string[];
  /** Task IDs this task replaces */
  supersedes: string[];
  /** Categorization tags */
  tags: string[];
  /** Increments when description changes */
  version: number;
  /** How this feature was created */
  origin: FeatureOrigin;
  /** Additional context or notes */
  notes: string;
  /** Last verification result (optional) */
  verification?: FeatureVerificationSummary;
  /**
   * E2E test tags for selective E2E test execution (optional)
   * Array of Playwright test tags to filter E2E tests
   * Used with Playwright's --grep flag for tag-based filtering
   *
   * Semantic meaning:
   * - undefined or not set: Skip E2E tests (feature has no UI)
   * - []: Skip E2E tests (explicit no-UI marker)
   * - ["@smoke"]: Run smoke E2E tests
   * - ["@feature-auth", "@login"]: Run specific feature E2E tests
   * - ["*"]: Run all E2E tests
   */
  e2eTags?: string[];
  /**
   * Test requirements for TDD workflow (optional)
   * When defined, verification uses test execution instead of AI analysis
   */
  testRequirements?: TestRequirements;
  /**
   * Actual test files created for this feature (written back after complete)
   * Populated by the complete command after verification passes
   */
  testFiles?: string[];
  /**
   * Cached TDD guidance from AI (optional)
   * Regenerated when feature.version changes
   */
  tddGuidance?: CachedTDDGuidance;
  /**
   * Task type classification for Universal Verification Strategy (UVS)
   * Determines which verification strategies are appropriate
   * Default: "code" (backward compatible - existing features are code tasks)
   */
  taskType?: TaskType;
  /**
   * Custom verification strategies for Universal Verification Strategy (UVS)
   * When defined, these strategies are used instead of default behavior
   * Supports: test, e2e, script, http, file, command, manual, ai, composite
   */
  verificationStrategies?: import("../verifier/types/index.js").VerificationStrategy[];
  /**
   * File patterns that affect this task (for task impact detection).
   * When files matching these patterns change, this task is flagged as potentially affected.
   * Supports glob patterns like "src/auth/**" or "src/utils/hash.ts".
   */
  affectedBy?: string[];
  /**
   * Custom file path relative to ai/tasks/ (for non-standard filenames).
   * Used when task files have custom names like "01-project-init.md" instead of derived from ID.
   * Preserved through load/save cycles to prevent data loss.
   */
  filePath?: string;
  /**
   * Raw markdown body content (excluding frontmatter).
   * Used to preserve custom sections during load/save cycles.
   * @internal - Not serialized to frontmatter, only used in memory.
   */
  rawBody?: string;
}

/**
 * Get the effective test pattern for a feature
 * Uses testRequirements.unit.pattern if available
 *
 * @param feature - The feature to get test pattern from
 * @returns Test pattern string or undefined
 */
export function getTestPattern(feature: Feature): string | undefined {
  return feature.testRequirements?.unit?.pattern;
}

// ============================================================================
// Feature List
// ============================================================================

/**
 * Feature list structure (in-memory representation)
 * Loaded from ai/tasks/ (modular) or legacy ai/feature_list.json
 */
export interface FeatureList {
  /** JSON Schema reference */
  $schema?: string;
  /** Array of features */
  features: Feature[];
  /** File metadata */
  metadata: FeatureListMetadata;
}

export interface FeatureListMetadata {
  /** Project goal description */
  projectGoal: string;
  /** ISO 8601 timestamp of creation */
  createdAt: string;
  /** ISO 8601 timestamp of last update */
  updatedAt: string;
  /** Schema version */
  version: string;
  /**
   * TDD enforcement mode (optional)
   * - strict: Tests REQUIRED, check/done fail without tests
   * - recommended: Tests suggested but not enforced (default)
   * - disabled: No TDD guidance
   */
  tddMode?: TDDMode;
}

// ============================================================================
// Task Type Aliases (Universal Verification Strategy)
// ============================================================================

/**
 * Task is an alias for Feature
 * Used in Universal Verification Strategy (UVS) to support non-code tasks
 * This alias enables gradual migration to task-centric terminology
 */
export type Task = Feature;

/**
 * TaskStatus is an alias for FeatureStatus
 */
export type TaskStatus = FeatureStatus;

/**
 * TaskOrigin is an alias for FeatureOrigin
 */
export type TaskOrigin = FeatureOrigin;

/**
 * TaskVerificationSummary is an alias for FeatureVerificationSummary
 */
export type TaskVerificationSummary = FeatureVerificationSummary;
