/**
 * Generate ai/init.sh bootstrap script
 */
import type { ProjectCommands } from "./types/index.js";
import type { ExtendedCapabilities } from "./verifier/types/index.js";

/**
 * Get install command based on package manager
 */
function getInstallCommand(packageManager?: string): string {
  switch (packageManager) {
    case "pnpm":
      return "pnpm install";
    case "yarn":
      return "yarn install";
    case "bun":
      return "bun install";
    case "pip":
      return "pip install -r requirements.txt";
    case "cargo":
      return "cargo build";
    case "go":
      return "go mod download";
    case "npm":
    default:
      return "npm install";
  }
}

/**
 * Get dev command based on package manager
 */
function getDevCommand(packageManager?: string): string {
  switch (packageManager) {
    case "pnpm":
      return "pnpm dev";
    case "yarn":
      return "yarn dev";
    case "bun":
      return "bun dev";
    case "cargo":
      return "cargo run";
    case "go":
      return "go run .";
    case "npm":
    default:
      return "npm run dev";
  }
}

/**
 * Fallback commands interface for generateInitScriptFromCapabilities
 */
export interface FallbackCommands {
  install?: string;
  dev?: string;
}

/**
 * E2E commands interface for init.sh generation
 */
export interface E2ECommands {
  /** Base E2E test command (e.g., "npx playwright test") */
  command?: string;
  /** Grep template for tag filtering (e.g., "npx playwright test --grep {tags}") */
  grepTemplate?: string;
}

/**
 * Generate init.sh script from ExtendedCapabilities
 * This is the primary function for generating init.sh from capabilities detection
 */
export function generateInitScriptFromCapabilities(
  caps: ExtendedCapabilities,
  fallbackCommands?: FallbackCommands
): string {
  const packageManager = caps.testInfo?.packageManager;

  const commands: ProjectCommands = {
    install: fallbackCommands?.install || getInstallCommand(packageManager),
    dev: fallbackCommands?.dev || getDevCommand(packageManager),
    build: caps.buildCommand || "",
    test: caps.testCommand || "",
    lint: caps.lintCommand,
  };

  // Extract E2E commands from capabilities
  const e2eCommands: E2ECommands | undefined = caps.e2eInfo?.available
    ? {
        command: caps.e2eInfo.command,
        grepTemplate: caps.e2eInfo.grepTemplate,
      }
    : undefined;

  // Use capabilities typeCheckCommand instead of hardcoded "npx tsc --noEmit"
  return generateInitScriptWithTypeCheck(commands, caps.typeCheckCommand, e2eCommands);
}


/**
 * Generate init.sh with explicit typecheck command support and E2E test support
 * Note: The check() function now delegates to agent-foreman check for unified verification
 */
export function generateInitScriptWithTypeCheck(
  commands: ProjectCommands,
  _typeCheckCommand?: string,
  _e2eCommands?: E2ECommands
): string {
  return `#!/usr/bin/env bash
# ai/init.sh - Bootstrap script for agent-foreman harness
# Generated by agent-foreman
set -euo pipefail

# Colors for output
RED='\\033[0;31m'
GREEN='\\033[0;32m'
YELLOW='\\033[1;33m'
NC='\\033[0m' # No Color

log_info() {
  echo -e "\${GREEN}[INFO]\${NC} \$1"
}

log_warn() {
  echo -e "\${YELLOW}[WARN]\${NC} \$1"
}

log_error() {
  echo -e "\${RED}[ERROR]\${NC} \$1"
}

# Bootstrap: Install dependencies
bootstrap() {
  log_info "Installing dependencies..."
  ${commands.install || "echo 'No install command configured'"}
  log_info "Bootstrap complete!"
}

# Dev: Start development environment
dev() {
  log_info "Starting development server..."
  ${commands.dev || "echo 'No dev command configured'"}
}

# Check: Delegate to agent-foreman check for unified verification
# All verification logic is centralized in agent-foreman check
# Usage: check [task_id] [--ai] [--full] [--verbose]
check() {
  # Check if agent-foreman is available
  if ! command -v agent-foreman &> /dev/null; then
    log_error "agent-foreman not found. Install with: npm install -g agent-foreman"
    exit 1
  fi

  log_info "Running verification via agent-foreman..."
  agent-foreman check "\$@"
}

# Build: Build for production
build() {
  log_info "Building for production..."
  ${commands.build || "echo 'No build command configured'"}
  log_info "Build complete!"
}

# Status: Show project status
status() {
  log_info "Project Status"
  echo "---"

  # Show feature list status if exists (check new format first, then legacy)
  if [ -f "ai/tasks/index.json" ]; then
    echo "Task Index: ai/tasks/index.json"
    local total=$(jq '.features | keys | length' ai/tasks/index.json)
    local passing=$(jq '[.features | to_entries[] | select(.value.status == "passing")] | length' ai/tasks/index.json)
    local failing=$(jq '[.features | to_entries[] | select(.value.status == "failing")] | length' ai/tasks/index.json)
    local review=$(jq '[.features | to_entries[] | select(.value.status == "needs_review")] | length' ai/tasks/index.json)
    echo "  Total: \$total"
    echo "  Passing: \$passing"
    echo "  Failing: \$failing"
    echo "  Needs Review: \$review"
  elif [ -f "ai/feature_list.json" ]; then
    echo "Feature List (legacy): ai/feature_list.json"
    local total=$(jq '.features | length' ai/feature_list.json)
    local passing=$(jq '[.features[] | select(.status == "passing")] | length' ai/feature_list.json)
    local failing=$(jq '[.features[] | select(.status == "failing")] | length' ai/feature_list.json)
    local review=$(jq '[.features[] | select(.status == "needs_review")] | length' ai/feature_list.json)
    echo "  Total: \$total"
    echo "  Passing: \$passing"
    echo "  Failing: \$failing"
    echo "  Needs Review: \$review"
  else
    log_warn "No feature list found. Run 'agent-foreman init' first."
  fi

  # Show recent progress log entries
  if [ -f "ai/progress.log" ]; then
    echo ""
    echo "Recent Progress:"
    tail -5 ai/progress.log
  fi
}

# Help
show_help() {
  echo "Usage: ./ai/init.sh <command> [options]"
  echo ""
  echo "Commands:"
  echo "  bootstrap             Install dependencies"
  echo "  dev                   Start development server"
  echo "  check [task_id]       Run verification (delegates to agent-foreman check)"
  echo "    (no args)           Fast mode: git diff based selective tests"
  echo "    [task_id]           Task mode: verify specific task"
  echo "    --ai                Fast mode + AI verification for affected tasks"
  echo "    --full              Full verification (all tests + build + E2E)"
  echo "    --verbose, -v       Show detailed output"
  echo "  build                 Build for production"
  echo "  status                Show project status"
  echo "  help                  Show this help message"
}

# Main entry point
case "\${1:-help}" in
  bootstrap)
    bootstrap
    ;;
  dev)
    dev
    ;;
  check)
    shift
    check "\$@"
    ;;
  build)
    build
    ;;
  status)
    status
    ;;
  help|--help|-h)
    show_help
    ;;
  *)
    log_error "Unknown command: \$1"
    show_help
    exit 1
    ;;
esac
`;
}

/**
 * Generate init.sh script content
 * @deprecated Use generateInitScriptFromCapabilities for new code
 */
export function generateInitScript(commands: ProjectCommands): string {
  // Delegate to the new function without explicit typecheck command (uses fallback detection)
  return generateInitScriptWithTypeCheck(commands);
}

/**
 * Generate minimal init.sh for projects without detected commands
 */
export function generateMinimalInitScript(): string {
  return `#!/usr/bin/env bash
# ai/init.sh - Bootstrap script for agent-foreman harness
# Generated by agent-foreman
set -euo pipefail

# Colors for output
RED='\\033[0;31m'
GREEN='\\033[0;32m'
YELLOW='\\033[1;33m'
NC='\\033[0m' # No Color

log_info() {
  echo -e "\${GREEN}[INFO]\${NC} \$1"
}

log_warn() {
  echo -e "\${YELLOW}[WARN]\${NC} \$1"
}

log_error() {
  echo -e "\${RED}[ERROR]\${NC} \$1"
}

# Bootstrap: Install dependencies
bootstrap() {
  log_info "Installing dependencies..."
  # TODO: Add your install command
  echo "Please configure install command in this script"
}

# Dev: Start development environment
dev() {
  log_info "Starting development server..."
  # TODO: Add your dev command
  echo "Please configure dev command in this script"
}

# Check: Delegate to agent-foreman check for unified verification
# All verification logic is centralized in agent-foreman check
# Usage: check [task_id] [--ai] [--full] [--verbose]
check() {
  # Check if agent-foreman is available
  if ! command -v agent-foreman &> /dev/null; then
    log_error "agent-foreman not found. Install with: npm install -g agent-foreman"
    exit 1
  fi

  log_info "Running verification via agent-foreman..."
  agent-foreman check "\$@"
}

# Build: Build for production
build() {
  log_info "Building for production..."
  # TODO: Add your build command
  echo "Please configure build command in this script"
}

# Status: Show project status
status() {
  log_info "Project Status"
  echo "---"

  # Check new format first, then legacy
  if [ -f "ai/tasks/index.json" ]; then
    echo "Task Index: ai/tasks/index.json"
    if command -v jq &> /dev/null; then
      local total=$(jq '.features | keys | length' ai/tasks/index.json)
      local passing=$(jq '[.features | to_entries[] | select(.value.status == "passing")] | length' ai/tasks/index.json)
      echo "  Total: \$total"
      echo "  Passing: \$passing"
    fi
  elif [ -f "ai/feature_list.json" ]; then
    echo "Feature List (legacy): ai/feature_list.json"
    if command -v jq &> /dev/null; then
      local total=$(jq '.features | length' ai/feature_list.json)
      local passing=$(jq '[.features[] | select(.status == "passing")] | length' ai/feature_list.json)
      echo "  Total: \$total"
      echo "  Passing: \$passing"
    fi
  else
    log_warn "No feature list found. Run 'agent-foreman init' first."
  fi
}

# Help
show_help() {
  echo "Usage: ./ai/init.sh <command> [options]"
  echo ""
  echo "Commands:"
  echo "  bootstrap             Install dependencies"
  echo "  dev                   Start development server"
  echo "  check [task_id]       Run verification (delegates to agent-foreman check)"
  echo "    (no args)           Fast mode: git diff based selective tests"
  echo "    [task_id]           Task mode: verify specific task"
  echo "    --ai                Fast mode + AI verification for affected tasks"
  echo "    --full              Full verification (all tests + build + E2E)"
  echo "    --verbose, -v       Show detailed output"
  echo "  build                 Build for production"
  echo "  status                Show project status"
  echo "  help                  Show this help message"
}

# Main entry point
case "\${1:-help}" in
  bootstrap)
    bootstrap
    ;;
  dev)
    dev
    ;;
  check)
    shift
    check "\$@"
    ;;
  build)
    build
    ;;
  status)
    status
    ;;
  help|--help|-h)
    show_help
    ;;
  *)
    log_error "Unknown command: \$1"
    show_help
    exit 1
    ;;
esac
`;
}
